# Clock
set_property PACKAGE_PIN AK34 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]

# Input: rst
set_property PACKAGE_PIN AY33 [get_ports rst]
    set_property IOSTANDARD LVCMOS18 [get_ports rst]

# Input: f_in
set_property PACKAGE_PIN AV30 [get_ports {f_in}]
    set_property IOSTANDARD LVCMOS18 [get_ports {f_in}]
    
# See VC707 board datasheet P68 for FMC 2 pins
# Input: a_in (FMC 2)
set_property PACKAGE_PIN AD32 [get_ports {a_in[0]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[0]}]
set_property PACKAGE_PIN AD33 [get_ports {a_in[1]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[1]}]
set_property PACKAGE_PIN Y32 [get_ports {a_in[2]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[2]}]
set_property PACKAGE_PIN Y33 [get_ports {a_in[3]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[3]}]
set_property PACKAGE_PIN AE29 [get_ports {a_in[4]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[4]}]
set_property PACKAGE_PIN AE30 [get_ports {a_in[5]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[5]}]
set_property PACKAGE_PIN AE32 [get_ports {a_in[6]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[6]}]
set_property PACKAGE_PIN AE33 [get_ports {a_in[7]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[7]}]
set_property PACKAGE_PIN AG36 [get_ports {a_in[8]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[8]}]
set_property PACKAGE_PIN AH36 [get_ports {a_in[9]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[9]}]
set_property PACKAGE_PIN AD36 [get_ports {a_in[10]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[10]}]
set_property PACKAGE_PIN AD37 [get_ports {a_in[11]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[11]}]
set_property PACKAGE_PIN AG34 [get_ports {a_in[12]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[12]}]
set_property PACKAGE_PIN AE37 [get_ports {a_in[13]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[13]}]
set_property PACKAGE_PIN AF37 [get_ports {a_in[14]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[14]}]
set_property PACKAGE_PIN AC35 [get_ports {a_in[15]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {a_in[15]}]

# Input: b_in (FMC 2)
set_property PACKAGE_PIN AC36 [get_ports {b_in[0]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[0]}]
set_property PACKAGE_PIN AD41 [get_ports {b_in[1]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[1]}]
set_property PACKAGE_PIN AJ42 [get_ports {b_in[2]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[2]}]
set_property PACKAGE_PIN AK42 [get_ports {b_in[3]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[3]}]
set_property PACKAGE_PIN AD42 [get_ports {b_in[4]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[4]}]
set_property PACKAGE_PIN U39 [get_ports {b_in[5]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[5]}]
set_property PACKAGE_PIN T39 [get_ports {b_in[6]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[6]}]
set_property PACKAGE_PIN AE42 [get_ports {b_in[7]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[7]}]
set_property PACKAGE_PIN AF29 [get_ports {b_in[8]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[8]}]
set_property PACKAGE_PIN AB33 [get_ports {b_in[9]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[9]}]
set_property PACKAGE_PIN AC33 [get_ports {b_in[10]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[10]}]
set_property PACKAGE_PIN AB29 [get_ports {b_in[11]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[11]}]
set_property PACKAGE_PIN AC29 [get_ports {b_in[12]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[12]}]
set_property PACKAGE_PIN AA31 [get_ports {b_in[13]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[13]}]
set_property PACKAGE_PIN AA32 [get_ports {b_in[14]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[14]}]
set_property PACKAGE_PIN AF34 [get_ports {b_in[15]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {b_in[15]}]

# See VC707 board datasheet P63 for FMC 1 pins
# Output: s_out (FMC 1)
set_property PACKAGE_PIN D35 [get_ports {s_out[0]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[0]}]
set_property PACKAGE_PIN D36 [get_ports {s_out[1]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[1]}]
set_property PACKAGE_PIN G32 [get_ports {s_out[2]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[2]}]
set_property PACKAGE_PIN F32 [get_ports {s_out[3]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[3]}]
set_property PACKAGE_PIN E32 [get_ports {s_out[4]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[4]}]
set_property PACKAGE_PIN D32 [get_ports {s_out[5]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[5]}]
set_property PACKAGE_PIN B36 [get_ports {s_out[6]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[6]}]
set_property PACKAGE_PIN A37 [get_ports {s_out[7]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[7]}]
set_property PACKAGE_PIN B39 [get_ports {s_out[8]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[8]}]
set_property PACKAGE_PIN A39 [get_ports {s_out[9]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[9]}]
set_property PACKAGE_PIN B34 [get_ports {s_out[10]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[10]}]
set_property PACKAGE_PIN A34 [get_ports {s_out[11]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[11]}]
set_property PACKAGE_PIN G28 [get_ports {s_out[12]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[12]}]
set_property PACKAGE_PIN G29 [get_ports {s_out[13]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[13]}]
set_property PACKAGE_PIN K27 [get_ports {s_out[14]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[14]}]
set_property PACKAGE_PIN J27 [get_ports {s_out[15]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {s_out[15]}]
