# Clock
set_property PACKAGE_PIN AK34 [get_ports CLK]
set_property IOSTANDARD LVCMOS18 [get_ports CLK]
create_clock -period 10.000 -name CLK -waveform {0.000 5.000} [get_ports CLK]

# Input: rst
set_property PACKAGE_PIN AY33 [get_ports RST]
    set_property IOSTANDARD LVCMOS18 [get_ports RST]

# Input: f_in
set_property PACKAGE_PIN AV30 [get_ports {F_IN}]
    set_property IOSTANDARD LVCMOS18 [get_ports {F_IN}]
    
# See VC707 board datasheet P68 for FMC 2 pins
# Input: A_in (FMC 2)
set_property PACKAGE_PIN AD32 [get_ports {A_IN[0]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[0]}]
set_property PACKAGE_PIN AD33 [get_ports {A_IN[1]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[1]}]
set_property PACKAGE_PIN Y32 [get_ports {A_IN[2]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[2]}]
set_property PACKAGE_PIN Y33 [get_ports {A_IN[3]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[3]}]
set_property PACKAGE_PIN AE29 [get_ports {A_IN[4]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[4]}]
set_property PACKAGE_PIN AE30 [get_ports {A_IN[5]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[5]}]
set_property PACKAGE_PIN AE32 [get_ports {A_IN[6]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[6]}]
set_property PACKAGE_PIN AE33 [get_ports {A_IN[7]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[7]}]
set_property PACKAGE_PIN AG36 [get_ports {A_IN[8]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[8]}]
set_property PACKAGE_PIN AH36 [get_ports {A_IN[9]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[9]}]
set_property PACKAGE_PIN AD36 [get_ports {A_IN[10]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[10]}]
set_property PACKAGE_PIN AD37 [get_ports {A_IN[11]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[11]}]
set_property PACKAGE_PIN AG34 [get_ports {A_IN[12]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[12]}]
set_property PACKAGE_PIN AE37 [get_ports {A_IN[13]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[13]}]
set_property PACKAGE_PIN AF37 [get_ports {A_IN[14]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[14]}]
set_property PACKAGE_PIN AC35 [get_ports {A_IN[15]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {A_IN[15]}]

# Input: B_in (FMC 2)
set_property PACKAGE_PIN AC36 [get_ports {B_IN[0]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[0]}]
set_property PACKAGE_PIN AD41 [get_ports {B_IN[1]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[1]}]
set_property PACKAGE_PIN AJ42 [get_ports {B_IN[2]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[2]}]
set_property PACKAGE_PIN AK42 [get_ports {B_IN[3]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[3]}]
set_property PACKAGE_PIN AD42 [get_ports {B_IN[4]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[4]}]
set_property PACKAGE_PIN U39 [get_ports {B_IN[5]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[5]}]
set_property PACKAGE_PIN T39 [get_ports {B_IN[6]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[6]}]
set_property PACKAGE_PIN AE42 [get_ports {B_IN[7]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[7]}]
set_property PACKAGE_PIN AF29 [get_ports {B_IN[8]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[8]}]
set_property PACKAGE_PIN AB33 [get_ports {B_IN[9]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[9]}]
set_property PACKAGE_PIN AC33 [get_ports {B_IN[10]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[10]}]
set_property PACKAGE_PIN AB29 [get_ports {B_IN[11]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[11]}]
set_property PACKAGE_PIN AC29 [get_ports {B_IN[12]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[12]}]
set_property PACKAGE_PIN AA31 [get_ports {B_IN[13]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[13]}]
set_property PACKAGE_PIN AA32 [get_ports {B_IN[14]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[14]}]
set_property PACKAGE_PIN AF34 [get_ports {B_IN[15]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {B_IN[15]}]

# See VC707 board datasheet P63 for FMC 1 pins
# Output: S_out (FMC 1)
set_property PACKAGE_PIN D35 [get_ports {S_OUT[0]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[0]}]
set_property PACKAGE_PIN D36 [get_ports {S_OUT[1]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[1]}]
set_property PACKAGE_PIN G32 [get_ports {S_OUT[2]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[2]}]
set_property PACKAGE_PIN F32 [get_ports {S_OUT[3]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[3]}]
set_property PACKAGE_PIN E32 [get_ports {S_OUT[4]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[4]}]
set_property PACKAGE_PIN D32 [get_ports {S_OUT[5]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[5]}]
set_property PACKAGE_PIN B36 [get_ports {S_OUT[6]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[6]}]
set_property PACKAGE_PIN A37 [get_ports {S_OUT[7]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[7]}]
set_property PACKAGE_PIN B39 [get_ports {S_OUT[8]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[8]}]
set_property PACKAGE_PIN A39 [get_ports {S_OUT[9]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[9]}]
set_property PACKAGE_PIN B34 [get_ports {S_OUT[10]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[10]}]
set_property PACKAGE_PIN A34 [get_ports {S_OUT[11]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[11]}]
set_property PACKAGE_PIN G28 [get_ports {S_OUT[12]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[12]}]
set_property PACKAGE_PIN G29 [get_ports {S_OUT[13]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[13]}]
set_property PACKAGE_PIN K27 [get_ports {S_OUT[14]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[14]}]
set_property PACKAGE_PIN J27 [get_ports {S_OUT[15]}]
    set_property IOSTANDARD LVCMOS18 [get_ports {S_OUT[15]}]
