webtalk_init -webtalk_dir /home/shuhangtan/Ece_498/CORDIC/adder2/adder2.sim/sim_1/behav/xsim/xsim.dir/a_s_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May  9 21:35:51 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174208431_1777515441_210730421_644" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a6e4a390-737c-4ad0-a83f-18f2485838c1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a1cbbc292541423594480662b2b3c45f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2430L 0 @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1212.524 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "132708_KB" -context "xsim\\usage"
webtalk_transmit -clientid 389723765 -regid "174208431_1777515441_210730421_644" -xml /home/shuhangtan/Ece_498/CORDIC/adder2/adder2.sim/sim_1/behav/xsim/xsim.dir/a_s_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/shuhangtan/Ece_498/CORDIC/adder2/adder2.sim/sim_1/behav/xsim/xsim.dir/a_s_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/shuhangtan/Ece_498/CORDIC/adder2/adder2.sim/sim_1/behav/xsim/xsim.dir/a_s_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
